title: Android Sensei
description: "A blog about Android, Life, the Universe and everything."

port: 3000
highlighter: rouge

permalink: /:year/:month/:day/:title.html
markdown: kramdown

google_analytics: UA-7443099-4

owner:
  name: Mihai Campean
  disqus_shortname: andr0idsensei
  twitter: r1k0
