title: Android Sensei
description: "A blog about Android, Life, the Universe and everything."

port: 3000
pygments: true

permalink: /:year/:month/:day/:title.html
markdown: redcarpet

google_analytics: #

owner:
  name: Mihai Campean
  disqus_shortname: andr0idsensei
  twitter: r1k0
